/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf --transform 
Files: scene.gltf [5.69KB] > scene-transformed.glb [624.35KB] (-10873%)
Author: Lawrence Pompey (https://sketchfab.com/lawrencepompey)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/leather-journal-3d-model-asset-df24ab0704e64ee7b5e1421cb49d88f5
Title: Leather Journal - 3D Model Asset
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Journal_journal_0.geometry} material={materials.journal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
