/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 pen.gltf --transform 
Files: pen.gltf [10.11KB] > pen-transformed.glb [19.6KB] (-94%)
Author: rafaelserralheiro (https://sketchfab.com/rafaelserralheiro)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/classic-pen-kaweco-f974e3e7c83d493ab8ed26e812567880
Title: Classic Pen Kaweco
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/pen-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder1_aiStandardSurface1_0.geometry} material={materials.aiStandardSurface1} position={[0.479, 4.256, 1.742]} rotation={[-0.492, 0.245, 1.34]} scale={[1.095, 1, 1.179]} />
      <mesh geometry={nodes.pCylinder1_aiStandardSurface2_0.geometry} material={materials.aiStandardSurface2} position={[0.479, 4.256, 1.742]} rotation={[-0.492, 0.245, 1.34]} scale={[1.095, 1, 1.179]} />
      <mesh geometry={nodes.pPlane1_lambert1_0.geometry} material={materials.lambert1} position={[-1.536, 43.327, 25.566]} rotation={[-Math.PI, 0.026, -Math.PI]} scale={[32.638, 1, 32.638]} />
    </group>
  )
}

useGLTF.preload('/pen-transformed.glb')
