/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.10 scene.gltf --transform 
Files: scene.gltf [4.43KB] > scene-transformed.glb [122.41KB] (-2663%)
Author: Milan (https://sketchfab.com/milanfonken)
License: CC-BY-NC-ND-4.0 (http://creativecommons.org/licenses/by-nc-nd/4.0/)
Source: https://sketchfab.com/3d-models/monalisa-fa55dc4f8b7f4ac398f3aee7b5e047bc
Title: Monalisa
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials.Material_27} position={[-8.494, 51.339, -15.709]} rotation={[0, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/scene-transformed.glb')
